version: "3.8"

services:
  api:
    image: freeauthapi
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file: ./.env
    ports:
      - 4000:4000
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file: ./.env
    volumes:
      - ./dbdata:/var/lib/postgresql/data
