version: "3.8"

services:
  freeauth-api:
    image: freeauthapi
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - freeauth-db
    env_file: ./.env.dev
    ports:
      - 4001:4001
  freeauth-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - ./dbdata:/var/lib/postgresql/data
